'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Department
    Public Property Id As Integer
    Public Property Name As String
    Public Property Location As String

    Public Overridable Property Employees As ObservableListSource(Of Employee) = New ObservableListSource(Of Employee)

End Class
